#!/bin/bash
/sbin/setuser abc /config/ts3server start
sleep 1s &&  cd /config/serverfiles/logs
exec /sbin/setuser abc tail -F -q --pid=$(cat /config/serverfiles/ts3server.pid) $(ls -t /config/serverfiles/logs | head -n 2)