#!/usr/bin/with-contenv bash

[[ ! -e /config/ts3server ]] && wget -O /config/ts3server http://gameservermanagers.com/dl/ts3server

chmod +x /config/ts3server
chown abc:abc -R /config


if [ ! -f /config/serverfiles/ts3server_minimal_runscript.sh ]; then
cd /config
s6-setuidgid abc /config/ts3server auto-install
fi


