#!/usr/bin/with-contenv bash

# make folders
mkdir -p /config/serverfiles

# fetch installer
if [ ! -e /config/ts3server ]; then
wget -O /config/ts3server http://gameservermanagers.com/dl/ts3server
chmod +x /config/ts3server
fi

# copy default config
if [ ! -e /config/serverfiles/ts3-server.ini ]; then
cp /defaults/ts3-server.ini /config/serverfiles/ts3-server.ini
chmod 440 /config/serverfiles/ts3-server.ini
fi

# permissions
chown abc:abc -R /config

if [ ! -f /config/serverfiles/ts3server_minimal_runscript.sh ]; then
cd /config
s6-setuidgid abc /config/ts3server auto-install
fi
